# -*- mode: ruby -*-
# vi: set ft=ruby :

box_url  = 'https://s3.amazonaws.com/easybibdeployment/imagineeasy-ubuntu-14.04.3_virtualbox-4.3.26r98988_chef-11.10.4_1.box'
box_file = 'imagineeasy-ubuntu-14.04.3_virtualbox-4.3.26r98988_chef-11.10.4_1'

Vagrant.configure("2") do |config|
  config.vm.box      = box_file
  config.vm.box_url  = box_url
  vagrant_boxname    = "Package Builder Box - php7"
  vagrant_memorysize = "1024"

  config.vm.provider :virtualbox do |vb|
     vb.gui = false
     vb.customize [
             "modifyvm", :id,
             "--name",   vagrant_boxname,
             "--memory", vagrant_memorysize
     ]
  end

  config.vm.provision :shell, :path => "./scripts/setup.sh"
  config.vm.synced_folder "./../", "/packaging", :owner => "vagrant", :nfs => false
  
end
